### PR TITLE
Changed button style naming scheme

### PR DESCRIPTION
**Pull request by aguscruiz**
Instead of naming them primary/secondary/etc. changed to a more direct naming like filled/outlined/text.  This was a requested change. Also minor changes to color shades

### CODE REVIEW

**Comment by aguscruiz** [comment]
@petemill @AlanBreck not urgent to merge this, and I don't know if it's final yet, but just a head's up on the naming change.

**Comment by AlanBreck** [comment]
Thanks! Let's wait until it's final as we'll have to change this throughout various repos.

**Comment by aguscruiz** [comment]
@AlanBreck @petemill I think this is ready to be merged, the biggest change is already done, any other minor ones shouldn't be a big deal

**Comment by AlanBreck** [comment]
Is this still valid?

**Comment by aguscruiz** [comment]
The newest PR has this and also new changes, thought this one was merged, sorry!

**Comment by AlanBreck** [comment]
Ok. Closing this one then.

**Pull request closed without merging**
